language: node_js
os: linux
node_js: 
  - '12'

cache: 
  directories:
    - ~/.npm
    - node_modules
git:
  depth: 3
script:
  - echo "deploying"
  - yarn build
  - firebase deploy --token $FIREBASE_TOKEN
install: 
  - npm install -g firebase-tools 
notifications:
  email:
    recipients:
      - adoa2705@gmail.com
  on_success: always
  on_failure: always

