language: node_js
os: linux
node_js: 
  - '12'

cache: 
  directories:
    - ~/.npm
    - node_modules
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
      - adoa2705@gmail.com
  on_success: always
  on_failure: always

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: cervew-eb41d
  message: "Hola:3"