language: node_js

node_js: 
  - '12'

cache: 
  directories:
    - ~/.npm
    - node_modules
git:
  depth: 3

install: 
  - yarn build
  
notifications:
  email:
    recipients:
      - adoa2705@gmail.com
  on_success: always
  on_failure: always

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: dist/
  message: "Hola:3"